name: Increment Version

on:
  push:
    branches:
      - dev

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.name "Julian querol"
      - run: git config --global user.email "julian.querol@abaigroup.com"
      - run: npm run update:release
      - run: git pull origin dev
